apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-helloapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-helloapp
  template:
    metadata:
      labels:
        app: k8s-helloapp
    spec:
      containers:
      - name: k8s-helloapp
        image: prabuddha66/helloapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
